[package]
name = "akio-syntax"
version = "0.1.0"
authors = ["Kyle Phelps <kphelps@salsify.com>"]

[lib]
proc-macro = true

[dependencies]
Inflector = "*"
syn = { version = "0.11", features = [ "full" ] }
synom = "0.11"
quote = "0.3"
