[package]
name = "akio-net"
version = "0.1.0"
authors = ["Kyle Phelps <kphelps@salsify.com>"]

[dependencies]
grpc = "0.*"
protobuf = "1.*"
futures = "0.1"
futures-cpupool = "0.1"

[build-dependencies]
protoc-rust-grpc = "0.*"
