closure_block_indent_threshold = 1
imports_indent = "Block"
imports_layout = "HorizontalVertical"
multiline_closure_forces_block = true
multiline_match_arm_forces_block = true
reorder_imported_names = true
reorder_imports = true
single_line_if_else_max_width = 0
struct_lit_multiline_style = "ForceMulti"
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
where_density = "Vertical"
