[package]
name = "indexing"
version = "0.1.0"
authors = ["Kyle Phelps <kylep91@gmail.com>"]

[dependencies]
akio = { path = "../../akio" }
akio-syntax = { path = "../../akio-syntax" }
uuid = { version = "0.4", features = ["v4"] }
